apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: web-server
        image: nginx:latest  # We hardcode the image here so Harness doesn't ask for it
