apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-example
  template:
    metadata:
      labels:
        app: harness-example
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: harness-example-svc
spec:
  type: NodePort
  selector:
    app: harness-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
