apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
      <+instance.labels>  # Add this line
  template:
    metadata:
      labels:
        app: web-server
        <+instance.labels>  # Add this line
    spec:
      containers:
      - name: web-server
        image: nginx:latest
